interface Bike {
  title: string;
  model: string;
  price: string;
  quantity: string;
  engine: string;
  dimension: string;
  displacement: string;
  clutch: string;
  transmission: string;
  horsePower: string;
  torque: string;
  boreAndStroke: string;
  fuelAverage: string;
  petrolCapacity: string;
  starting: string;
  topSpeed: string;
  type: string;
}

export const bikesData: Bike[] = [
    {
      title: 'Honda Pridor',
      model: 'Honda CG 125 2024',
      price: '$17790',
      quantity: '10',
      engine: '4-Stroke OHC Air-Cooled',
      displacement: '100 CC',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      fuelAverage: '45.0 KM/L',
      petrolCapacity: '9.7L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'New',
    },
    {
      title: 'Benelli TRK',
      model: 'Benelli TRK 502X 2024',
      price: '$29500',
      quantity: '10',
      engine: 'V2, Four-stroke',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      displacement: '500 CC',
      fuelAverage: '20.0 KM/L',
      petrolCapacity: '20L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'Old',
    },
    {
      title: 'Benelli TRK',
      model: 'Benelli TRK 502X 2024',
      price: '$29500',
      quantity: '10',
      engine: 'V2, Four-stroke',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      displacement: '500 CC',
      fuelAverage: '20.0 KM/L',
      petrolCapacity: '20L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'New',
    },
    {
      title: 'BMW S1000RR',
      model: 'BMW S1000RR',
      price: '$17790',
      quantity: '10',
      engine: '4-stroke 16-valve DOHC inline-',
      displacement: '999 CC',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      fuelAverage: '15.0 KM/L',
      petrolCapacity: '17.5L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'Old',
    },
    {
      title: 'BMW S1000RR',
      model: 'BMW S1000RR',
      price: '$17790',
      quantity: '10',
      engine: '4-stroke 16-valve DOHC inline-',
      displacement: '999 CC',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      fuelAverage: '15.0 KM/L',
      petrolCapacity: '17.5L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'New',
    },
    {
      title: 'Benelli TRK',
      model: 'Benelli TRK 502X 2024',
      price: '$29500',
      quantity: '10',
      engine: 'V2, Four-stroke',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      displacement: '500 CC',
      fuelAverage: '20.0 KM/L',
      petrolCapacity: '20L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'Old',
    },
    {
      title: 'Benelli TRK',
      model: 'Benelli TRK 502X 2024',
      price: '$29500',
      quantity: '10',
      engine: 'V2, Four-stroke',
      displacement: '500 CC',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      fuelAverage: '20.0 KM/L',
      petrolCapacity: '20L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'New',
    },
    {
      title: 'BMW S1000RR',
      model: 'BMW S1000RR',
      price: '$17790',
      quantity: '10',
      engine: '4-stroke 16-valve DOHC inline-',
      displacement: '999 CC',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      fuelAverage: '15.0 KM/L',
      petrolCapacity: '17.5L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'Old',
    },
    {
      title: 'BMW S1000RR',
      model: 'BMW S1000RR',
      price: '$17790',
      quantity: '10',
      engine: '4-stroke 16-valve DOHC inline-',
      displacement: '999 CC',
      dimension: '1986 x 718 x 1050 mm',
      clutch: 'Multiple wet plates',
      transmission: '4-speed',
      horsePower: '7.5 HP @ 8500.0 RPM',
      torque: '7.2 Nm @ 5500.0 RPM',
      boreAndStroke: '50.0 x 49.5 mm',
      fuelAverage: '15.0 KM/L',
      petrolCapacity: '17.5L',
      starting: 'Kick start',
      topSpeed: '100 KM/H',
      type: 'New',
    },
  ];